{% set name = "aiida-core" %}
{% set version = "1.0.0b1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdc69bc25678ba4d72cdfa000867b59fbb0d72721d599685b1b29dd579545621

build:
  number: 2
  entry_points:
    - verdi=aiida.cmdline.verdilib:run
  script: "python -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [win or py==3.7]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - reentry==1.2.2
    - python-dateutil==2.8.0
    - python-mimeparse==1.6.0
    - django==1.11.20
    - tzlocal==1.5.1
    - pytz==2018.9
    - PyYAML==3.13
    - six==1.12.0
    - anyjson==0.3.3
    - psutil==5.5.1
    - meld3==1.0.2
    - mock==2.0.0
    - numpy==1.16.1
    - SQLAlchemy==1.2.18
    - SQLAlchemy-Utils==0.33.11
    - alembic==1.0.7
    - ujson==1.35
    - aldjemy==0.9.1
    - passlib==1.7.1
    - click==7.0
    - click-completion==0.5.0
    - click-plugins==1.0.4
    - click-spinner==0.1.8
    - tabulate==0.8.3
    - ete3==3.1.1
    - uritools==2.2.0
    - psycopg2==2.7.6
    - paramiko==2.4.2
    - ecdsa==0.13
    - ipython>=4.0,<6.0
    - plumpy==0.12.1
    - kiwipy[rmq]==0.4.2
    - pika==1.0.0b1
    - circus==0.15.0
    - tornado<5.0
    - simplejson==3.16.0

outputs:

  - name: aiida-core
    test:
      imports:
        - aiida
        - aiida.cmdline
        - aiida.common
        - aiida.manage
        - aiida.restapi
        - aiida.scheduler
        - aiida.transport
      commands:
        - verdi --help
        - verdi --version
        - verdi status

  - name: aiida-core.services
    requirements:
      run:
        - postgresql>=9.6
        - rabbitmq-server
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida_core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
