{% set name = "aiida-core" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee352597ef37dc1a98bb4ad099ceeeee897e4b3bedfde367305a8e79a8aade8e

build:
  number: 0
  noarch: python
  entry_points:
    - verdi=aiida.cmdline.commands.cmd_verdi:verdi
  script: 'python -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - python ~=3.7
    - aldjemy ~=0.9.1
    - alembic ~=1.2
    - archive-path ~=0.2.1
    - aio-pika ~=6.6
    - circus ~=0.17.1
    - click-completion ~=0.5.1
    - click-config-file ~=0.6.0
    - click-spinner ~=0.1.8
    - click ~=7.1
    - django ~=2.2
    - ete3 ~=3.1
    - python-graphviz ~=0.13
    - ipython ~=7.20
    - jinja2 ~=2.10
    - jsonschema ~=3.0
    - kiwipy[rmq] ~=0.7.4
    - numpy ~=1.17
    - pamqp ~=2.3
    - paramiko ~=2.7,>=2.7.2
    - plumpy ~=0.19.0
    - pgsu ~=0.1.0
    - psutil ~=5.6
    - psycopg2 ~=2.8,>=2.8.3
    - python-dateutil ~=2.8
    - pytz ~=2019.3
    - pyyaml ~=5.1.2
    - reentry ~=1.3
    - simplejson ~=3.16
    - sqlalchemy-utils ~=0.36.0
    - sqlalchemy ~=1.3.10
    - tabulate ~=0.8.5
    - tqdm ~=4.45
    - tzlocal ~=2.0
    - upf_to_json ~=0.9.2
    - wrapt ~=1.11.1
  run_constrained:
    - aiida-core.services =={{ version }}

test:
  imports:
    - aiida
    - aiida.common
    - aiida.common.hashing
    - aiida.manage
    - aiida.restapi
    - aiida.schedulers
    - aiida.transports
    - aiida.tools
    - aiida.tools.importexport
  commands:
    - reentry scan -r aiida
    - verdi --help
    - verdi --version

outputs:
  - name: aiida-core
  - name: aiida-core.services
    build:
      noarch: python
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server >=3.7
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida-core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
    - sphuber
