# Set Version and Build-Number
{% set version = "2.0.1" %}
{% set build = 5 %}

# Set names for the AiiDA Meta-Package and accompanying Sub-Packages
{% set aiidameta = "aiida" %}
{% set aiidacore = "aiida-core" %}
{% set aiidaservice = "aiida-core.services" %}
{% set aiida_atomic_tools = "aiida-core.atomic_tools" %}
{% set aiida_notebook = "aiida-core.notebook" %}
{% set aiida_rest = "aiida-core.rest" %}

# Define the Source and AiiDA Meta-Package
package:
  name: {{ aiidameta|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ aiidacore[0] }}/{{ aiidacore }}/{{ aiidacore }}-{{ version }}.tar.gz
  sha256: 7b0a09bc02dee38410f6fc7dd0a679789bb60c0bcc2b75212e9668c727f6e966

build:
  number: {{ build }}
  noarch: python

# Packages that shall be shipped when installing from the Meta-Package are
# defined here
requirements:
  run:
    - {{ pin_subpackage(aiidacore, exact=True) }}
    - {{ pin_subpackage(aiidaservice, exact=True) }}

# Define the available Sub-Packages
outputs:
  - name: {{ aiidacore }}
    build:
      noarch: python
      entry_points:
        - verdi=aiida.cmdline.commands.cmd_verdi:verdi
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - python
        - pip
        - flit-core
      run:
        - python ~=3.8
        - alembic ~=1.2
        - archive-path ~=0.4.0
        - aio-pika ~=6.6
        - circus ~=0.17.1
        - click-config-file ~=0.6.0
        - click-spinner ~=0.1.8
        - click ~=8.1
        - disk-objectstore ~=0.6.0
        - python-graphviz ~=0.13
        - ipython ~=7.20
        - jinja2 ~=3.0
        - jsonschema ~=3.0
        - kiwipy[rmq] ~=0.7.5
        - importlib-metadata ~=4.3
        - numpy ~=1.19
        - pamqp ~=2.3
        - paramiko ~=2.7,>=2.7.2
        - plumpy ~=0.21.0
        - pgsu ~=0.2.1
        - psutil ~=5.6
        - psycopg2-binary ~=2.8
        - pytz ~=2021.1
        - pyyaml ~=5.4
        - sqlalchemy ~=1.4.22
        - tabulate ~=0.8.5
        - tqdm ~=4.45
        - upf_to_json ~=0.9.2
        - wrapt ~=1.11.1
      run_constrained:
        - {{ pin_subpackage(aiidaservice, exact=True) }}
    test:
      requires:
        - pip
      imports:
        - aiida
        - aiida.common
        - aiida.common.hashing
        - aiida.manage
        - aiida.restapi
        - aiida.schedulers
        - aiida.transports
        - aiida.tools
        - aiida.tools.dbexporters
        - aiida.tools.dbimporters
      commands:
        - verdi --help
        - verdi --version
        - pip check
    
  - name: {{ aiidaservice }}
    build:
      noarch: python
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server >=3.7,<3.8.15
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

  - name: {{ aiida_atomic_tools }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - ase ~=3.18
        - matplotlib-base ~=3.3,>=3.3.4
        - pycifrw ~=4.4
        - pymatgen >=2019.7.2,<=2022.1.9,!=2019.9.7
        - pymysql ~=0.9.3
        - seekpath ~=1.9,>=1.9.3
        - spglib ~=1.14
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: {{ aiida_notebook }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - jupyter_client ~=6.1,<6.1.13
        - jupyter ~=1.0
        - notebook ~=6.1,>=6.1.5
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: {{ aiida_rest }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - flask-cors ~=3.0
        - flask-restful ~=0.3.7
        - flask ~=2.0
        - pyparsing ~=2.4
        - python-memcached ~=1.59
        - seekpath ~=1.9,>=1.9.3
    test:
      requires:
        - pip
      commands:
        - pip check

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida-core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
    - sphuber
