{% set name = "aiida-core" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 899fdf941542d33e840a2a8c8598f18f57af742ee1a94f7b814283a169fe923d

build:
  number: 0
  entry_points:
    - verdi=aiida.cmdline.commands.cmd_verdi:verdi
  script: "python -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [win or py > 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aldjemy ==0.9.1
    - alembic ==1.2.1
    - circus ==0.15.0
    - click-completion ==0.5.1
    - click-config-file ==0.5.0
    - click-spinner ==0.1.8
    - click ==7.0
    - django ==1.11.25
    - ete3 ==3.1.1
    - enum34 ==1.1.6  # [py < 35]
    - python-graphviz ==0.13
    - ipython >=4.0,<6.0
    - kiwipy[rmq] ==0.5.1
    - mock ==3.0.5
    - numpy ==1.16.4
    - paramiko ==2.6.0
    - passlib ==1.7.1
    - pika ==1.1.0
    - plumpy ==0.14.3
    - psutil ==5.6.3
    - psycopg2 ==2.8.3
    - pyblake2 ==1.1.2  # [py < 36]
    - python-dateutil ==2.8.0
    - pytz ==2019.3
    - pyyaml ==3.13
    - reentry >=1.3.0
    - simplejson ==3.16.0
    - singledispatch >=3.4.0.3  # [py < 35]
    - six ==1.12.0
    - typing ==3.7.4.1  # [py < 35]
    - sqlalchemy-utils ==0.34.2
    - sqlalchemy ==1.3.10
    - tabulate ==0.8.5
    - tornado <5.0
    - tzlocal ==2.0.0
    - upf_to_json ==0.9.2
    - uritools ==2.2.0
    - wrapt ==1.11.2

test:
  imports:
    - aiida
    - aiida.cmdline
    - aiida.common
    - aiida.common.hashing
    - aiida.manage
    - aiida.restapi
    - aiida.schedulers
    - aiida.transports
  commands:
    - reentry scan -r aiida
    - verdi --help
    - verdi --version

outputs:
  - name: aiida-core
  - name: aiida-core.services
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida-core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
    - sphuber
