{% set name = "aiida-core" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e58cac7aaf4d69d8c7b99107bec999b7b2c2f99a964e6aa1904a7f6d4148161

build:
  number: 0
  entry_points:
    - verdi=aiida.cmdline.commands.cmd_verdi:verdi
  script: 'python -m pip install . --no-deps --ignore-installed -vvv '
  skip: true  # [win or py < 35 or py > 38]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aldjemy ~=0.9.1
    - alembic ~=1.2
    - circus ~=0.16.1
    - click-completion ~=0.5.1
    - click-config-file ~=0.5.0
    - click-spinner ~=0.1.8
    - click ~=7.0
    - django ~=2.2
    - ete3 ~=3.1
    - python-graphviz ~=0.13
    - ipython ~=7.0
    - jinja2 ~=2.10
    - kiwipy[rmq] ~=0.5.1
    - numpy ~=1.17,<1.18
    - paramiko ~=2.6
    - pika ~=1.1
    - plumpy ~=0.14.5
    - pgsu ~=0.1.0
    - psutil ~=5.6
    - psycopg2 ~=2.8,>=2.8.3
    - python-dateutil ~=2.8
    - pytz ~=2019.3
    - pyyaml ~=5.1.2
    - reentry ~=1.3
    - simplejson ~=3.16
    - sqlalchemy-utils ~=0.34.2
    - sqlalchemy ~=1.3,>=1.3.10
    - tabulate ~=0.8.5
    - tornado <5.0
    - tzlocal ~=2.0
    - upf_to_json ~=0.9.2
    - wrapt ~=1.11.1

test:
  imports:
    - aiida
    - aiida.common
    - aiida.common.hashing
    - aiida.manage
    - aiida.restapi
    - aiida.schedulers
    - aiida.transports
  commands:
    - reentry scan -r aiida
    - verdi --help
    - verdi --version

outputs:
  - name: aiida-core
  - name: aiida-core.services
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida-core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
    - sphuber
