{% set name = "aiida-core" %}
{% set version = "1.0.0b6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a66d119db0dd827f1e28b8265c0f7aa953f0aa0003472e754b146011e90e8efe

build:
  number: 0
  entry_points:
    - verdi=aiida.cmdline.commands.cmd_verdi:verdi
  script: "python -m pip install . --no-deps --ignore-installed -vvv "
  # remove the python limit when py37 build error is understood
  # https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=30238
  skip: True  # [win or py > 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - reentry >=1.3.0
    - python-dateutil ==2.8.0
    - django ==1.11.20
    - tzlocal ==1.5.1
    - pytz ==2018.9
    - PyYAML ==3.13
    - six ==1.12.0
    - psutil ==5.5.1
    - mock ==2.0.0
    - numpy ==1.16.4
    - SQLAlchemy ==1.3.3
    - SQLAlchemy-Utils ==0.33.11
    - alembic ==1.0.7
    - aldjemy ==0.9.1
    - passlib ==1.7.1
    - click ==7.0
    - click-completion ==0.5.1
    - click-config-file ==0.5.0
    - click-spinner ==0.1.8
    - tabulate ==0.8.3
    - ete3 ==3.1.1
    - uritools ==2.2.0
    - psycopg2 ==2.8
    - paramiko ==2.6.0
    - ipython >=4.0,<6.0
    - plumpy ==0.14.2
    - kiwipy[rmq] ==0.5.1
    - pika ==1.0.0
    - circus ==0.15.0
    - tornado <5.0
    - pyblake2 ==1.1.2  # [py < 36]
    - singledispatch >=3.4.0.3  # [py < 35]
    - enum34 ==1.1.6  # [py < 35]
    - simplejson ==3.16.0
    - typing ==3.6.6  # [py < 35]
    - wrapt ==1.11.1
    - python-graphviz ==0.10.1

test:
  imports:
    - aiida
    - aiida.cmdline
    - aiida.common
    - aiida.common.hashing
    - aiida.manage
    - aiida.restapi
    - aiida.schedulers
    - aiida.transports
  commands:
    - reentry scan -r aiida
    - verdi --help
    - verdi --version

outputs:

  - name: aiida-core
  - name: aiida-core.services
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida_core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
