# Set Version and Build-Number
{% set version = "2.7.0rc0" %}
{% set build = 0 %}

# Set package metainfo
{% set python_min = "3.9" %}

# Set names for the AiiDA Meta-Package and accompanying Sub-Packages
{% set aiidameta = "aiida" %}
{% set aiidacore = "aiida-core" %}
{% set aiidaservice = "aiida-core.services" %}
{% set aiida_atomic_tools = "aiida-core.atomic_tools" %}
{% set aiida_notebook = "aiida-core.notebook" %}
{% set aiida_rest = "aiida-core.rest" %}

# Define the Source and AiiDA Meta-Package
package:
  name: {{ aiidameta|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ aiidacore[0] }}/{{ aiidacore }}/aiida_core-{{ version }}.tar.gz
  sha256: 553b213f1a2b5ef028917459ab6e3f31de5824fd50ca4ff80dacab04fd38de8b

build:
  number: {{ build }}
  noarch: python

# Define the available Sub-Packages
outputs:
  - name: {{ aiidacore }}
    build:
      noarch: python
      entry_points:
        - verdi=aiida.cmdline.commands.cmd_verdi:verdi
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - flit-core
      run:
        - python >={{ python_min }}
        - alembic ~=1.2
        - archive-path ~=0.4.2
        - asyncssh ~=2.19.0
        - circus ~=0.19.0
        - click-spinner ~=0.1.8
        - click ~=8.1
        - disk-objectstore ~=1.3.0
        - docstring_parser
        - get-annotations ~=0.1
        - python-graphviz ~=0.19
        - plumpy ~=0.25.0
        - ipython >=7
        - jedi <0.19
        - jinja2 ~=3.0
        - kiwipy[rmq] ~=0.8.4
        - importlib-metadata ~=6.0
        - numpy ~=1.21
        - paramiko ~=3.0
        - pgsu ~=0.3.0
        - psutil ~=5.6
        - psycopg[binary] ~=3.0
        - pydantic ~=2.4
        - pytz ~=2021.1
        - pyyaml ~=6.0
        - requests ~=2.0
        - sqlalchemy ~=2.0
        - tabulate <0.10.0,>=0.8.0
        - tqdm ~=4.45
        - typing-extensions ~=4.0
        - upf_to_json ~=0.9.2
        - wrapt ~=1.11
        - chardet ~=5.2.0
      run_constrained:
        - {{ pin_subpackage(aiidaservice) }}
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - aiida
        - aiida.common
        - aiida.common.hashing
        - aiida.manage
        - aiida.restapi
        - aiida.schedulers
        - aiida.transports
        - aiida.tools
        - aiida.tools.dbexporters
        - aiida.tools.dbimporters
      commands:
        - verdi --help
        - verdi --version
        - pip check

  - name: {{ aiidaservice }}
    build:
      noarch: python
    requirements:
      run:
        - postgresql >=9.6
        - rabbitmq-server >=3.11
    test:
      commands:
        - postgres --help
        - rabbitmqctl help

  - name: {{ aiida_atomic_tools }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - ase ~=3.18
        - matplotlib-base ~=3.3,>=3.3.4
        - pycifrw ~=4.4
        - pymatgen >=2022.1.20
        - pymysql ~=0.9.3
        - seekpath ~=1.9,>=1.9.3
        - spglib >=1.14,<3.0
    test:
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check

  - name: {{ aiida_notebook }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - jupyter_client ~=8.0
        - jupyter ~=1.0
        - notebook ~=6.1,>=6.1.5
    test:
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check

  - name: {{ aiida_rest }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - python >={{ python_min }}
        - flask-cors ~=3.0
        - flask-restful ~=0.3.7
        - flask ~=2.2
        - pyparsing ~=2.4
        - python-memcached ~=1.59
        - seekpath ~=1.9,>=1.9.3
    test:
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check

  - name: {{ aiidameta }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      # Packages that shall be shipped when installing from the Meta-Package are defined here
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(aiidacore, exact=True) }}
        - {{ pin_subpackage(aiidaservice, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - pip check

about:
  home: http://aiida.net
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: AiiDA, an automated interactive infrastructure and database for computational science
  doc_url: https://aiida-core.readthedocs.io
  dev_url: https://github.com/aiidateam/aiida-core

extra:
  recipe-maintainers:
    - ltalirz
    - astamminger
    - chrisjsewell
    - sphuber
    - agoscinski
    - unkcpz
    - khsrali
    - GeigerJ2
    - giovannipizzi
    - danielhollas
