appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ORlpjuZtEiSX+xRr4xJcn99RVeuAS8S9rIylsjKz03FtgfecgNrykX6HnTocfNRu9YmCzY90ybuAyCNcokbjLszBDR+W6OTFjqzy7HMkGVhymhvhxjaNxBavNLQUAPz+EktUnnnl55qKjF3eVR+Z0Av9W2AQMJQBUIHsu+7iSIvDTCyS5aPvivaNjI9i8IXVw1HSVj18mYeogRDmb2QDxsjsNWEnSli8DbKNV9aJYKAGntm493Yetnl77FVkhNP+QJwhtpfEUx1F2zzQxi8gz88ZHIkf0r4BeYqAPLHKT8WT2eQWyPBjjE1zElAQJ/ViwJsvOaxKsmw1skhNMwbhk0oWjMmnPLVGDLsnLlbAg4Qrau907T02Gbsn5zX808hCJrtXhb6SHw4EVhDlZSOQje5KlKMgxh07FjnWAfTY4/mrszwGwo0SD/aT2Ylh2iSdQxUFToB7RVdd2sap8VDU3hI4Ao+XUZkGVRLgBsrjefQEjysbCc0lxUHkA57UeP4Q2apF0z+vaLSeUHKG+4KEJ6+cxaagG+nZa+9eMa7ZcriznZX76EUSTZZomvngVL0LS0i7fDc2XkkEzskpLvgHTF0j89cWD7tanMTpfwCrUfwWzV5qkRqBoTbaw0z0XlFbB421R+nPysKNfq7Q5WCty8TsS7n5VfkvfF1FFFP7wns=}
provider:
  win: azure
conda_forge_output_validation: true
